// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: client_event.proto

package chat

import (
	_ "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT        MessageType = 1
	MessageType_MESSAGE_TYPE_POST        MessageType = 2
	MessageType_MESSAGE_TYPE_IMAGE       MessageType = 3
	MessageType_MESSAGE_TYPE_FILE        MessageType = 4
	MessageType_MESSAGE_TYPE_AUDIO       MessageType = 5
	MessageType_MESSAGE_TYPE_VIDEO       MessageType = 6
	MessageType_MESSAGE_TYPE_STICKER     MessageType = 7
	MessageType_MESSAGE_TYPE_CARD        MessageType = 8
	MessageType_MESSAGE_TYPE_AI_CHAT     MessageType = 9
	MessageType_MESSAGE_TYPE_SYSTEM      MessageType = 10
	MessageType_MESSAGE_TYPE_DELETE      MessageType = 11
	MessageType_MESSAGE_TYPE_RTC         MessageType = 12
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNSPECIFIED",
		1:  "MESSAGE_TYPE_TEXT",
		2:  "MESSAGE_TYPE_POST",
		3:  "MESSAGE_TYPE_IMAGE",
		4:  "MESSAGE_TYPE_FILE",
		5:  "MESSAGE_TYPE_AUDIO",
		6:  "MESSAGE_TYPE_VIDEO",
		7:  "MESSAGE_TYPE_STICKER",
		8:  "MESSAGE_TYPE_CARD",
		9:  "MESSAGE_TYPE_AI_CHAT",
		10: "MESSAGE_TYPE_SYSTEM",
		11: "MESSAGE_TYPE_DELETE",
		12: "MESSAGE_TYPE_RTC",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_TEXT":        1,
		"MESSAGE_TYPE_POST":        2,
		"MESSAGE_TYPE_IMAGE":       3,
		"MESSAGE_TYPE_FILE":        4,
		"MESSAGE_TYPE_AUDIO":       5,
		"MESSAGE_TYPE_VIDEO":       6,
		"MESSAGE_TYPE_STICKER":     7,
		"MESSAGE_TYPE_CARD":        8,
		"MESSAGE_TYPE_AI_CHAT":     9,
		"MESSAGE_TYPE_SYSTEM":      10,
		"MESSAGE_TYPE_DELETE":      11,
		"MESSAGE_TYPE_RTC":         12,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_event_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_client_event_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{0}
}

type SendMsgEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	RoomId  string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MsgType MessageType            `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3,enum=zhongshangwu.avatarai.social.MessageType" json:"msg_type,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*SendMsgEvent_Payload
	//	*SendMsgEvent_AiChatBody
	Body          isSendMsgEvent_Body `protobuf_oneof:"body"`
	SenderId      string              `protobuf:"bytes,5,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ThreadId      string              `protobuf:"bytes,6,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	QuoteId       string              `protobuf:"bytes,7,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	SenderAt      string              `protobuf:"bytes,8,opt,name=sender_at,json=senderAt,proto3" json:"sender_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMsgEvent) Reset() {
	*x = SendMsgEvent{}
	mi := &file_client_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMsgEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgEvent) ProtoMessage() {}

func (x *SendMsgEvent) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgEvent.ProtoReflect.Descriptor instead.
func (*SendMsgEvent) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{0}
}

func (x *SendMsgEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendMsgEvent) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *SendMsgEvent) GetBody() isSendMsgEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SendMsgEvent) GetPayload() string {
	if x != nil {
		if x, ok := x.Body.(*SendMsgEvent_Payload); ok {
			return x.Payload
		}
	}
	return ""
}

func (x *SendMsgEvent) GetAiChatBody() *AIChatMessageBody {
	if x != nil {
		if x, ok := x.Body.(*SendMsgEvent_AiChatBody); ok {
			return x.AiChatBody
		}
	}
	return nil
}

func (x *SendMsgEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendMsgEvent) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SendMsgEvent) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *SendMsgEvent) GetSenderAt() string {
	if x != nil {
		return x.SenderAt
	}
	return ""
}

type isSendMsgEvent_Body interface {
	isSendMsgEvent_Body()
}

type SendMsgEvent_Payload struct {
	Payload string `protobuf:"bytes,3,opt,name=payload,json=body,proto3,oneof"`
}

type SendMsgEvent_AiChatBody struct {
	AiChatBody *AIChatMessageBody `protobuf:"bytes,4,opt,name=ai_chat_body,json=body,proto3,oneof"`
}

func (*SendMsgEvent_Payload) isSendMsgEvent_Body() {}

func (*SendMsgEvent_AiChatBody) isSendMsgEvent_Body() {}

type AIChatMessageItemMessage struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Id            string                              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                              `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // 常量: "message"
	Role          string                              `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // 常量: "user"
	Content       []*AIChatMessageItemMessage_Content `protobuf:"bytes,4,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIChatMessageItemMessage) Reset() {
	*x = AIChatMessageItemMessage{}
	mi := &file_client_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIChatMessageItemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatMessageItemMessage) ProtoMessage() {}

func (x *AIChatMessageItemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatMessageItemMessage.ProtoReflect.Descriptor instead.
func (*AIChatMessageItemMessage) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{1}
}

func (x *AIChatMessageItemMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AIChatMessageItemMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AIChatMessageItemMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AIChatMessageItemMessage) GetContent() []*AIChatMessageItemMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type AIChatMessageItemFunctionCall struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Id            string                                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // 常量: "function_call"
	Function      *AIChatMessageItemFunctionCall_Function `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIChatMessageItemFunctionCall) Reset() {
	*x = AIChatMessageItemFunctionCall{}
	mi := &file_client_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIChatMessageItemFunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatMessageItemFunctionCall) ProtoMessage() {}

func (x *AIChatMessageItemFunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatMessageItemFunctionCall.ProtoReflect.Descriptor instead.
func (*AIChatMessageItemFunctionCall) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{2}
}

func (x *AIChatMessageItemFunctionCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AIChatMessageItemFunctionCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AIChatMessageItemFunctionCall) GetFunction() *AIChatMessageItemFunctionCall_Function {
	if x != nil {
		return x.Function
	}
	return nil
}

type AIChatMessageBody struct {
	state           protoimpl.MessageState                 `protogen:"open.v1"`
	Id              string                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role            string                                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content         string                                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Status          int32                                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	InterruptType   int32                                  `protobuf:"varint,5,opt,name=interrupt_type,json=interruptType,proto3" json:"interrupt_type,omitempty"`
	Error           string                                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	MessageItems    []*AIChatMessageBody_AIChatMessageItem `protobuf:"bytes,7,rep,name=message_items,json=messageItems,proto3" json:"message_items,omitempty"`
	MessageMetadata *_struct.Struct                        `protobuf:"bytes,8,opt,name=message_metadata,json=messageMetadata,proto3" json:"message_metadata,omitempty"` // 消息元数据, 包含 Usage 等
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AIChatMessageBody) Reset() {
	*x = AIChatMessageBody{}
	mi := &file_client_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIChatMessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatMessageBody) ProtoMessage() {}

func (x *AIChatMessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatMessageBody.ProtoReflect.Descriptor instead.
func (*AIChatMessageBody) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{3}
}

func (x *AIChatMessageBody) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AIChatMessageBody) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AIChatMessageBody) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AIChatMessageBody) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AIChatMessageBody) GetInterruptType() int32 {
	if x != nil {
		return x.InterruptType
	}
	return 0
}

func (x *AIChatMessageBody) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AIChatMessageBody) GetMessageItems() []*AIChatMessageBody_AIChatMessageItem {
	if x != nil {
		return x.MessageItems
	}
	return nil
}

func (x *AIChatMessageBody) GetMessageMetadata() *_struct.Struct {
	if x != nil {
		return x.MessageMetadata
	}
	return nil
}

type ClientEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventId   string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientEvent_SendMsg
	Event         isClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_client_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{4}
}

func (x *ClientEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ClientEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ClientEvent) GetEvent() isClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientEvent) GetSendMsg() *SendMsgEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_SendMsg); ok {
			return x.SendMsg
		}
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_SendMsg struct {
	SendMsg *SendMsgEvent `protobuf:"bytes,3,opt,name=send_msg,json=event,proto3,oneof"`
}

func (*ClientEvent_SendMsg) isClientEvent_Event() {}

type AIChatMessageItemMessage_ImageUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIChatMessageItemMessage_ImageUrl) Reset() {
	*x = AIChatMessageItemMessage_ImageUrl{}
	mi := &file_client_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIChatMessageItemMessage_ImageUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatMessageItemMessage_ImageUrl) ProtoMessage() {}

func (x *AIChatMessageItemMessage_ImageUrl) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatMessageItemMessage_ImageUrl.ProtoReflect.Descriptor instead.
func (*AIChatMessageItemMessage_ImageUrl) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AIChatMessageItemMessage_ImageUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AIChatMessageItemMessage_ImageUrl) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type AIChatMessageItemMessage_Content struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Content       string                             `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ImageUrl      *AIChatMessageItemMessage_ImageUrl `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIChatMessageItemMessage_Content) Reset() {
	*x = AIChatMessageItemMessage_Content{}
	mi := &file_client_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIChatMessageItemMessage_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatMessageItemMessage_Content) ProtoMessage() {}

func (x *AIChatMessageItemMessage_Content) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatMessageItemMessage_Content.ProtoReflect.Descriptor instead.
func (*AIChatMessageItemMessage_Content) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{1, 1}
}

func (x *AIChatMessageItemMessage_Content) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AIChatMessageItemMessage_Content) GetImageUrl() *AIChatMessageItemMessage_ImageUrl {
	if x != nil {
		return x.ImageUrl
	}
	return nil
}

type AIChatMessageItemFunctionCall_Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIChatMessageItemFunctionCall_Function) Reset() {
	*x = AIChatMessageItemFunctionCall_Function{}
	mi := &file_client_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIChatMessageItemFunctionCall_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatMessageItemFunctionCall_Function) ProtoMessage() {}

func (x *AIChatMessageItemFunctionCall_Function) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatMessageItemFunctionCall_Function.ProtoReflect.Descriptor instead.
func (*AIChatMessageItemFunctionCall_Function) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AIChatMessageItemFunctionCall_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AIChatMessageItemFunctionCall_Function) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type AIChatMessageBody_AIChatMessageItem struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Message       *AIChatMessageItemMessage      `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	FunctionCall  *AIChatMessageItemFunctionCall `protobuf:"bytes,2,opt,name=function_call,json=functionCall,proto3" json:"function_call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIChatMessageBody_AIChatMessageItem) Reset() {
	*x = AIChatMessageBody_AIChatMessageItem{}
	mi := &file_client_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIChatMessageBody_AIChatMessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIChatMessageBody_AIChatMessageItem) ProtoMessage() {}

func (x *AIChatMessageBody_AIChatMessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_client_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIChatMessageBody_AIChatMessageItem.ProtoReflect.Descriptor instead.
func (*AIChatMessageBody_AIChatMessageItem) Descriptor() ([]byte, []int) {
	return file_client_event_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AIChatMessageBody_AIChatMessageItem) GetMessage() *AIChatMessageItemMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AIChatMessageBody_AIChatMessageItem) GetFunctionCall() *AIChatMessageItemFunctionCall {
	if x != nil {
		return x.FunctionCall
	}
	return nil
}

var File_client_event_proto protoreflect.FileDescriptor

const file_client_event_proto_rawDesc = "" +
	"\n" +
	"\x12client_event.proto\x12\x1czhongshangwu.avatarai.social\x1a\x1cgoogle/protobuf/struct.proto\x1a google/protobuf/descriptor.proto\"\xcf\x02\n" +
	"\fSendMsgEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12D\n" +
	"\bmsg_type\x18\x02 \x01(\x0e2).zhongshangwu.avatarai.social.MessageTypeR\amsgType\x12\x17\n" +
	"\apayload\x18\x03 \x01(\tH\x00R\x04body\x12M\n" +
	"\fai_chat_body\x18\x04 \x01(\v2/.zhongshangwu.avatarai.social.AIChatMessageBodyH\x00R\x04body\x12\x1b\n" +
	"\tsender_id\x18\x05 \x01(\tR\bsenderId\x12\x1b\n" +
	"\tthread_id\x18\x06 \x01(\tR\bthreadId\x12\x19\n" +
	"\bquote_id\x18\a \x01(\tR\aquoteId\x12\x1b\n" +
	"\tsender_at\x18\b \x01(\tR\bsenderAtB\x06\n" +
	"\x04body\"\xe6\x02\n" +
	"\x18AIChatMessageItemMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12X\n" +
	"\acontent\x18\x04 \x03(\v2>.zhongshangwu.avatarai.social.AIChatMessageItemMessage.ContentR\acontent\x1a4\n" +
	"\bImageUrl\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x1a\x81\x01\n" +
	"\aContent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\\\n" +
	"\timage_url\x18\x02 \x01(\v2?.zhongshangwu.avatarai.social.AIChatMessageItemMessage.ImageUrlR\bimageUrl\"\xe3\x01\n" +
	"\x1dAIChatMessageItemFunctionCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12`\n" +
	"\bfunction\x18\x03 \x01(\v2D.zhongshangwu.avatarai.social.AIChatMessageItemFunctionCall.FunctionR\bfunction\x1a<\n" +
	"\bFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"\x9c\x04\n" +
	"\x11AIChatMessageBody\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12%\n" +
	"\x0einterrupt_type\x18\x05 \x01(\x05R\rinterruptType\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12f\n" +
	"\rmessage_items\x18\a \x03(\v2A.zhongshangwu.avatarai.social.AIChatMessageBody.AIChatMessageItemR\fmessageItems\x12B\n" +
	"\x10message_metadata\x18\b \x01(\v2\x17.google.protobuf.StructR\x0fmessageMetadata\x1a\xc7\x01\n" +
	"\x11AIChatMessageItem\x12P\n" +
	"\amessage\x18\x01 \x01(\v26.zhongshangwu.avatarai.social.AIChatMessageItemMessageR\amessage\x12`\n" +
	"\rfunction_call\x18\x02 \x01(\v2;.zhongshangwu.avatarai.social.AIChatMessageItemFunctionCallR\ffunctionCall\"\x97\x01\n" +
	"\vClientEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12E\n" +
	"\bsend_msg\x18\x03 \x01(\v2*.zhongshangwu.avatarai.social.SendMsgEventH\x00R\x05eventB\a\n" +
	"\x05event*\xcb\x02\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x15\n" +
	"\x11MESSAGE_TYPE_POST\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x03\x12\x15\n" +
	"\x11MESSAGE_TYPE_FILE\x10\x04\x12\x16\n" +
	"\x12MESSAGE_TYPE_AUDIO\x10\x05\x12\x16\n" +
	"\x12MESSAGE_TYPE_VIDEO\x10\x06\x12\x18\n" +
	"\x14MESSAGE_TYPE_STICKER\x10\a\x12\x15\n" +
	"\x11MESSAGE_TYPE_CARD\x10\b\x12\x18\n" +
	"\x14MESSAGE_TYPE_AI_CHAT\x10\t\x12\x17\n" +
	"\x13MESSAGE_TYPE_SYSTEM\x10\n" +
	"\x12\x17\n" +
	"\x13MESSAGE_TYPE_DELETE\x10\v\x12\x14\n" +
	"\x10MESSAGE_TYPE_RTC\x10\fB4Z2github.com/zhongshangwu/avatarai-social/proto/chatb\x06proto3"

var (
	file_client_event_proto_rawDescOnce sync.Once
	file_client_event_proto_rawDescData []byte
)

func file_client_event_proto_rawDescGZIP() []byte {
	file_client_event_proto_rawDescOnce.Do(func() {
		file_client_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_event_proto_rawDesc), len(file_client_event_proto_rawDesc)))
	})
	return file_client_event_proto_rawDescData
}

var file_client_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_event_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_client_event_proto_goTypes = []any{
	(MessageType)(0),                               // 0: zhongshangwu.avatarai.social.MessageType
	(*SendMsgEvent)(nil),                           // 1: zhongshangwu.avatarai.social.SendMsgEvent
	(*AIChatMessageItemMessage)(nil),               // 2: zhongshangwu.avatarai.social.AIChatMessageItemMessage
	(*AIChatMessageItemFunctionCall)(nil),          // 3: zhongshangwu.avatarai.social.AIChatMessageItemFunctionCall
	(*AIChatMessageBody)(nil),                      // 4: zhongshangwu.avatarai.social.AIChatMessageBody
	(*ClientEvent)(nil),                            // 5: zhongshangwu.avatarai.social.ClientEvent
	(*AIChatMessageItemMessage_ImageUrl)(nil),      // 6: zhongshangwu.avatarai.social.AIChatMessageItemMessage.ImageUrl
	(*AIChatMessageItemMessage_Content)(nil),       // 7: zhongshangwu.avatarai.social.AIChatMessageItemMessage.Content
	(*AIChatMessageItemFunctionCall_Function)(nil), // 8: zhongshangwu.avatarai.social.AIChatMessageItemFunctionCall.Function
	(*AIChatMessageBody_AIChatMessageItem)(nil),    // 9: zhongshangwu.avatarai.social.AIChatMessageBody.AIChatMessageItem
	(*_struct.Struct)(nil),                         // 10: google.protobuf.Struct
}
var file_client_event_proto_depIdxs = []int32{
	0,  // 0: zhongshangwu.avatarai.social.SendMsgEvent.msg_type:type_name -> zhongshangwu.avatarai.social.MessageType
	4,  // 1: zhongshangwu.avatarai.social.SendMsgEvent.ai_chat_body:type_name -> zhongshangwu.avatarai.social.AIChatMessageBody
	7,  // 2: zhongshangwu.avatarai.social.AIChatMessageItemMessage.content:type_name -> zhongshangwu.avatarai.social.AIChatMessageItemMessage.Content
	8,  // 3: zhongshangwu.avatarai.social.AIChatMessageItemFunctionCall.function:type_name -> zhongshangwu.avatarai.social.AIChatMessageItemFunctionCall.Function
	9,  // 4: zhongshangwu.avatarai.social.AIChatMessageBody.message_items:type_name -> zhongshangwu.avatarai.social.AIChatMessageBody.AIChatMessageItem
	10, // 5: zhongshangwu.avatarai.social.AIChatMessageBody.message_metadata:type_name -> google.protobuf.Struct
	1,  // 6: zhongshangwu.avatarai.social.ClientEvent.send_msg:type_name -> zhongshangwu.avatarai.social.SendMsgEvent
	6,  // 7: zhongshangwu.avatarai.social.AIChatMessageItemMessage.Content.image_url:type_name -> zhongshangwu.avatarai.social.AIChatMessageItemMessage.ImageUrl
	2,  // 8: zhongshangwu.avatarai.social.AIChatMessageBody.AIChatMessageItem.message:type_name -> zhongshangwu.avatarai.social.AIChatMessageItemMessage
	3,  // 9: zhongshangwu.avatarai.social.AIChatMessageBody.AIChatMessageItem.function_call:type_name -> zhongshangwu.avatarai.social.AIChatMessageItemFunctionCall
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_client_event_proto_init() }
func file_client_event_proto_init() {
	if File_client_event_proto != nil {
		return
	}
	file_client_event_proto_msgTypes[0].OneofWrappers = []any{
		(*SendMsgEvent_Payload)(nil),
		(*SendMsgEvent_AiChatBody)(nil),
	}
	file_client_event_proto_msgTypes[4].OneofWrappers = []any{
		(*ClientEvent_SendMsg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_event_proto_rawDesc), len(file_client_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_event_proto_goTypes,
		DependencyIndexes: file_client_event_proto_depIdxs,
		EnumInfos:         file_client_event_proto_enumTypes,
		MessageInfos:      file_client_event_proto_msgTypes,
	}.Build()
	File_client_event_proto = out.File
	file_client_event_proto_goTypes = nil
	file_client_event_proto_depIdxs = nil
}
