server:
  # domain: "http://127.0.0.1:8082"
  domain: "https://avatarai.social"
  http:
          #address: "127.0.0.1:8082"
    address: "0.0.0.0:8082"
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "60s"
  https:
    enabled: true
    address: "127.0.0.1:443"
    cert_file: "certs/server.crt"
    key_file: "certs/server.key"
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "60s"
  metrics:
    address: ":8081"
  admin_key: ""

database:
  driver: "sqlite"
  dsn: "./data/avatarai.sqlite"
  max_connections: 20
  max_idle_connections: 5
  connection_lifetime: "1h"
  connection_timeout: "30s"

storage:
  data_dir: "data/avatarai"

app:
  bundle_id: "com.example.avatarai"

atp:
  service: "default"
  client_jwk_secret: '{"crv":"P-256","x":"irkBy9VtQSTCTXzdWDR98HHFrks5oEBxvZtlw9nY9Q8","y":"7G_cb4yzueSrlijJBOn0gQVww5wII_G-SYY2n5HPZHQ","d":"vqmUbiz9XofGSQnfRMJeVEO_o3peCTw8NK44doQRsMY","kty":"EC","kid":"demo-1743489358"}'

avatar:
  llm:
    provider: "openai"
    api_url: "https://openrouter.ai/api/v1"
    model: "mistralai/ministral-3b"
    api_key: "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"

security:
  rsa_private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDXugRatTJYghRE
    CALnRnY9cR2x9ayOUwK3DVY+j9rrv3Rc6kMIjkqURk7dO33SOkv6Yp5hAbD+b5yY
    Oy/kuJNVJu5zwopDmrjZsJXe5GbyjK/DV0M1U6LgsWpcJ1VVh3mr35gmeaAnF4qb
    fYTA0InKqZPMQ0SyfFZLS0JNiHJoo1le39xZtoR92BZjAut56SyfAcuJzqA+MYCe
    CWuGMNyenUQer6Jngv0WYEIYGaxUiL9fqKznylDUYF1/Bw1zmMVuSGQFfNZMur7/
    bwCGy5zhXv7l+GsPwAliQrUr6AspWrXRgmUwi4/YdpjbusDwwWaP8pZGeHhWdH1J
    nGAYPk39AgMBAAECggEAOn3P125gz7m5V/baHq4uuhsVA58Koe5lApAFreHgaGJZ
    YSYNdeDq3Mgxcu/B/kHbPvEFY2ULgfluOqJ1qmzXWdO7/LwnNAxcCX5FLJG+Tg6S
    S4M6EFf0hjrkjUcG7rFUbqMqBGie4WqTJPTEDWmdqssO7Wfh1Qk8dp7Zw972smL0
    Zk2gYSN9/G96uVhWpui7NSZ0nuey0ZMZzrUdVjVI3FATcreKeCm2O85B6BG5VX+J
    yg7Vi64Mdbby3rQgNH9A94Poy3jsiK7pwRahlZfHbT+PuTnihOzfsBwaXI+xkf4Z
    HEo2Hm6mdrgCKJ1XwSqgqsWgNevup6A6JhCyi9zyiwKBgQD36Q96z023M/aC8XPc
    CqwjYOz5cvKiZHs0TqdZ7ybDihVNAxumhXDoFqkMF2KgX+fKWdisKWmzg00DskLc
    TtQP3rv7Bua3KZVtZBMkaIwtMzKJiRPvRIOxO0WTymXNOBXlmEF3eRbYQyueLyxa
    GumL0XLlSRju7kYEKF+ynz7zxwKBgQDexBtbrF4q/4HMQHPhz+bjtvkOFoms951I
    VFNhZCzAl8FqW2+asx+u9o9yBDTvFNKGxiPpzP+0rjsN8GxMRuJSnmko3zZwe7Re
    /3VSOnNuBfCDNfTyaDSe52S1NKyeDdtC2iwC6CWPm0AeSSDa37/epIE/Xtx/2r7R
    NU7K3mCoGwKBgFYbWigS1vB6GPY0PUTBZDbJlKWz2jizY+OwKgpfuXwTewCLws/c
    63GBZWfwu23uwciT2mE55R/XzCkrgnOY4ak9eNdg90PJKsCbENcFhSKx9Ky2svjZ
    OFCXwLvrgd58y4Y6kwqXQWsOMZk401Pcox/QOPMQp5tdoW4SQ+L70tbDAoGBAKVu
    IxcAOWpbFuw1DRmryD5hWjFRIWrW8/GL1ePkfauExzkRsB7FWQkYx0wXvauy3ekC
    ahctitOF9AsU+YfnuBk81MFqikYcR8Wollq7V49kT8lRH5eJNVKwakR7WpmBlsvd
    s4NxHLu5wnL7Qa/pK9bOecEy1DMKolxA50OWw1bzAoGAS6n2OnKamejg0YSlJsHk
    aMu2KqEYZMHCoyB1Iq+oEZNf0NQw01VkpJaF0syNQlmqv19HpKWiENinZGCE1mho
    YjrqUrJpbd0jBJadp/ZDOXanLXSydmfR9acngRusuSlwLi7lP/yk5M3TabqAYF/T
    kOGkhUvntYvLpBrQs98PiQk=
    -----END PRIVATE KEY-----
mcp:
  servers:
    - mcpId: "notion-mcp"
      name: "Notion MCP Server"
      description: "通过 Notion MCP Server 访问和同步您的 Notion 页面和数据库，支持页面读取、数据库查询、内容搜索等功能"
      version: "1.0.0"
      author: "AvatarAI"
      endpoint:
        type: "streamableHttp"
        url: "https://notion.mcp.avatarai.social/mcp"
        headers: {}
      authorization:
        method: "oauth2"
        scopes: "user"
        client_id: "15ed872b-594c-817b-a08c-0037362900ad"
        client_secret: "secret_jW7WOpp8VtximCQIgPeZmvzLLoH2gZpnt7Pu8WdYDcq"
        redirect_uri: "https://avatarai.social/api/mcp/oauth/callback"
        client_type: "confidential"

    - mcpId: "github-mcp"
      name: "GitHub MCP Server"
      description: "GitHub MCP Server 允许您使用GitHub API 和第三方客户端（如Cursor）进行交互。要使用GitHub MCP，您需要在GitHub中创建集成，获取内部集成令牌，并在MCP客户端中配置这些信息，以便客户端可以访问和操作您的GitHub仓库。"
      version: "1.2.0"
      author: "AvatarAI"
      endpoint:
        type: "streamableHttp"
        url: "https://github.mcp.avatarai.social/mcp"
        headers: {}
      authorization:
        method: "oauth2"
        scopes: "repo"
        client_id: "Ov23liXZ68YbB4ILHsyg"
        client_secret: "a7c79cea7177603c833e8b310736a81a8d033f6b"
        redirect_uri: "https://avatarai.social/api/mcp/oauth/callback"
        client_type: "public"

    - mcpId: "twitter-mcp"
      name: "Twitter MCP Server"
      description: "通过 X MCP Server 访问您的推文、时间线和社交互动数据，支持发布推文、获取时间线、分析互动等功能"
      version: "1.0.0"
      author: "AvatarAI"
      endpoint:
        type: "streamableHttp"
        url: "https://x.mcp.avatarai.social/mcp"
        headers: {}
      authorization:
        method: "oauth2"
        scopes: "tweet.read tweet.write users.read offline.access follows.read follows.write like.read like.write media.write"
        client_id: "VC1yaFhoWktuVzhEdGxTUjF6VEI6MTpjaQ"
        client_secret: "EjdsctDBgUAaKOYmtTrKtlawGxtBYYQA5qk29XCnwSJfFhHFJH"
        redirect_uri: "https://avatarai.social/api/mcp/oauth/callback"
        client_type: "public"
