// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.activity.relationship

import (
	comatprototypes "github.com/bluesky-social/indigo/api/atproto"
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.vtri.activity.relationship", &ActivityRelationship{})
} //
// RECORDTYPE: ActivityRelationship
type ActivityRelationship struct {
	LexiconTypeID string                         `json:"$type,const=app.vtri.activity.relationship" cborgen:"$type,const=app.vtri.activity.relationship"`
	CreatedAt     string                         `json:"createdAt" cborgen:"createdAt"`
	Creator       *comatprototypes.RepoStrongRef `json:"creator,omitempty" cborgen:"creator,omitempty"`
	Object        *comatprototypes.RepoStrongRef `json:"object" cborgen:"object"`
	Predicate     string                         `json:"predicate" cborgen:"predicate"`
	Subject       *comatprototypes.RepoStrongRef `json:"subject" cborgen:"subject"`
}
