// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.activity.tag

import (
	comatprototypes "github.com/bluesky-social/indigo/api/atproto"
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.vtri.activity.tag", &ActivityTag{})
} //
// RECORDTYPE: ActivityTag
type ActivityTag struct {
	LexiconTypeID string                         `json:"$type,const=app.vtri.activity.tag" cborgen:"$type,const=app.vtri.activity.tag"`
	CreatedAt     string                         `json:"createdAt" cborgen:"createdAt"`
	Creator       *comatprototypes.RepoStrongRef `json:"creator,omitempty" cborgen:"creator,omitempty"`
	Tag           *string                        `json:"tag,omitempty" cborgen:"tag,omitempty"`
}
