// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.activity.like

import (
	comatprototypes "github.com/bluesky-social/indigo/api/atproto"
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.vtri.activity.like", &ActivityLike{})
} //
// RECORDTYPE: ActivityLike
type ActivityLike struct {
	LexiconTypeID string                         `json:"$type,const=app.vtri.activity.like" cborgen:"$type,const=app.vtri.activity.like"`
	CreatedAt     string                         `json:"createdAt" cborgen:"createdAt"`
	Subject       *comatprototypes.RepoStrongRef `json:"subject" cborgen:"subject"`
}
