// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.activity.topic

import (
	comatprototypes "github.com/bluesky-social/indigo/api/atproto"
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.vtri.activity.topic", &ActivityTopic{})
} //
// RECORDTYPE: ActivityTopic
type ActivityTopic struct {
	LexiconTypeID string                         `json:"$type,const=app.vtri.activity.topic" cborgen:"$type,const=app.vtri.activity.topic"`
	CreatedAt     string                         `json:"createdAt" cborgen:"createdAt"`
	Creator       *comatprototypes.RepoStrongRef `json:"creator,omitempty" cborgen:"creator,omitempty"`
	Topic         string                         `json:"topic" cborgen:"topic"`
}
