// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.avatar.profile

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.vtri.avatar.profile", &AvatarProfile{})
} //
// RECORDTYPE: AvatarProfile
type AvatarProfile struct {
	LexiconTypeID string `json:"$type,const=app.vtri.avatar.profile" cborgen:"$type,const=app.vtri.avatar.profile"`
	// avatar: 头像图片
	Avatar *util.LexBlob `json:"avatar,omitempty" cborgen:"avatar,omitempty"`
	// banner: 个人页面背景图片
	Banner    *util.LexBlob `json:"banner,omitempty" cborgen:"banner,omitempty"`
	CreatedAt *string       `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	// description: 个人简介
	Description *string `json:"description,omitempty" cborgen:"description,omitempty"`
	Did         *string `json:"did,omitempty" cborgen:"did,omitempty"`
	DisplayName *string `json:"displayName,omitempty" cborgen:"displayName,omitempty"`
	Handle      *string `json:"handle,omitempty" cborgen:"handle,omitempty"`
}
