// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.chat.thread

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.vtri.chat.thread", &ChatThread{})
} //
// RECORDTYPE: ChatThread
type ChatThread struct {
	LexiconTypeID string `json:"$type,const=app.vtri.chat.thread" cborgen:"$type,const=app.vtri.chat.thread"`
	// createdAt: 创建时间
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// deleted: 是否被删除
	Deleted *bool `json:"deleted,omitempty" cborgen:"deleted,omitempty"`
	// id: 话题ID
	Id string `json:"id" cborgen:"id"`
	// title: 话题标题
	Title string `json:"title" cborgen:"title"`
	// type: 话题类型: 连续上下文/独立上下文
	Type string `json:"type" cborgen:"type"`
	// updatedAt: 更新时间
	UpdatedAt string `json:"updatedAt" cborgen:"updatedAt"`
}
