// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.entity.images

import (
	appbskytypes "github.com/bluesky-social/indigo/api/bsky"
	"github.com/bluesky-social/indigo/lex/util"
)

// EntityImages is a "main" in the app.vtri.entity.images schema.
type EntityImages struct {
	Images []*EntityImages_Image `json:"images" cborgen:"images"`
}

// EntityImages_Image is a "image" in the app.vtri.entity.images schema.
type EntityImages_Image struct {
	// alt: Alt text description of the image, for accessibility.
	Alt         string                              `json:"alt" cborgen:"alt"`
	AspectRatio *appbskytypes.EmbedDefs_AspectRatio `json:"aspectRatio,omitempty" cborgen:"aspectRatio,omitempty"`
	Image       *util.LexBlob                       `json:"image" cborgen:"image"`
}
