// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.entity.record

import (
	comatprototypes "github.com/bluesky-social/indigo/api/atproto"
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.vtri.entity.record#main", &EntityRecord{})
} // EntityRecord is a "main" in the app.vtri.entity.record schema.
// RECORDTYPE: EntityRecord
type EntityRecord struct {
	LexiconTypeID string                         `json:"$type,const=app.vtri.entity.record" cborgen:"$type,const=app.vtri.entity.record"`
	Record        *comatprototypes.RepoStrongRef `json:"record" cborgen:"record"`
}
