// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.entity.defs

// EntityDefs_AspectRatio is a "aspectRatio" in the app.vtri.entity.defs schema.
//
// width:height represents an aspect ratio. It may be approximate, and may not correspond to absolute dimensions in any given unit.
type EntityDefs_AspectRatio struct {
	Height int64 `json:"height" cborgen:"height"`
	Width  int64 `json:"width" cborgen:"width"`
}
