// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.entity.video

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.vtri.entity.video#main", &EntityVideo{})
} // EntityVideo is a "main" in the app.vtri.entity.video schema.
// RECORDTYPE: EntityVideo
type EntityVideo struct {
	LexiconTypeID string `json:"$type,const=app.vtri.entity.video" cborgen:"$type,const=app.vtri.entity.video"`
	// alt: Alt text description of the video, for accessibility.
	Alt         *string                 `json:"alt,omitempty" cborgen:"alt,omitempty"`
	AspectRatio *EntityDefs_AspectRatio `json:"aspectRatio,omitempty" cborgen:"aspectRatio,omitempty"`
	Captions    []*EntityVideo_Caption  `json:"captions,omitempty" cborgen:"captions,omitempty"`
	// video: The mp4 video file. May be up to 100mb, formerly limited to 50mb.
	Video *util.LexBlob `json:"video" cborgen:"video"`
}

// EntityVideo_Caption is a "caption" in the app.vtri.entity.video schema.
type EntityVideo_Caption struct {
	File *util.LexBlob `json:"file" cborgen:"file"`
	Lang string        `json:"lang" cborgen:"lang"`
}
