// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.entity.external

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.vtri.entity.external#main", &EntityExternal{})
} // EntityExternal is a "main" in the app.vtri.entity.external schema.
// A representation of some externally linked content (eg, a URL and 'card'), embedded in a vtri record (eg, a moment).
//
// RECORDTYPE: EntityExternal
type EntityExternal struct {
	LexiconTypeID string                   `json:"$type,const=app.vtri.entity.external" cborgen:"$type,const=app.vtri.entity.external"`
	External      *EntityExternal_External `json:"external" cborgen:"external"`
}

// EntityExternal_External is a "external" in the app.vtri.entity.external schema.
type EntityExternal_External struct {
	Description string        `json:"description" cborgen:"description"`
	Thumb       *util.LexBlob `json:"thumb,omitempty" cborgen:"thumb,omitempty"`
	Title       string        `json:"title" cborgen:"title"`
	Uri         string        `json:"uri" cborgen:"uri"`
}
