// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package vtri

// schema: app.vtri.entity.file

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.vtri.entity.file", &EntityFile{})
} //
// RECORDTYPE: EntityFile
type EntityFile struct {
	LexiconTypeID string        `json:"$type,const=app.vtri.entity.file" cborgen:"$type,const=app.vtri.entity.file"`
	Blob          *util.LexBlob `json:"blob,omitempty" cborgen:"blob,omitempty"`
	// createdAt: 创建时间
	CreatedAt *int64 `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
	// updatedAt: 更新时间
	UpdatedAt *int64 `json:"updatedAt,omitempty" cborgen:"updatedAt,omitempty"`
}
